### ISSUE TITLE
Add semver check for crates

### ISSUE THREAD

**Issue by jw3** [ctc-oss/fapolicy-analyzer#704]
Need an automated check to prevent failure to bump crate versions.

See https://github.com/obi1kenobi/cargo-semver-checks

There is an action https://github.com/obi1kenobi/cargo-semver-checks-action

**Comment by jw3** [comment]
`cargo semver-checks check-release --workspace --baseline-rev HEAD`

Index checks against HEAD

workflow example

```yaml
  semver-check:
    if: github.ref != 'refs/heads/master'
    needs: [fmt]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-semver-checks
      - run: cargo semver-checks check-release
```
